services:
  frontend:
    build: .
    ports:
      - "${HOST_PORT:-80}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080}
      - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY:-09c90650-1760-4d00-b33d-13c52db8c3fa}
    restart: unless-stopped
