export const SHELL_CACHE = 'cityhawk-shell-v2';
export const DATA_CACHE = 'cityhawk-data-v2';
export const STATIC_CACHE = 'cityhawk-static-v2';
export const HANDLEBARS_CDN_URL = 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.8/handlebars.min.js';

const TEMPLATE_URLS = [
  '/src/components/event-card/event-card.hbs',
  '/src/components/form-controls/form-input.hbs',
  '/src/components/form-controls/form-select.hbs',
  '/src/components/footer/footer.hbs',
  '/src/components/header/header.hbs',
  '/src/components/support-launcher/support-launcher-panel.hbs',
  '/src/modules/events/details/event-description.hbs',
  '/src/modules/events/delete/event-delete-card.hbs',
  '/src/modules/events/delete/event-delete-screen.hbs',
  '/src/modules/events/form/event-edit-intro.hbs',
  '/src/modules/events/form/event-editor-screen.hbs',
  '/src/modules/events/form/event-form.hbs',
  '/src/modules/events/details/event-gallery.hbs',
  '/src/modules/events/details/event-hero.hbs',
  '/src/modules/events/list/event-list-catalog.hbs',
  '/src/modules/events/list/event-list-filters.hbs',
  '/src/modules/events/details/event-location.hbs',
  '/src/modules/events/details/event-recommendations.hbs',
  '/src/modules/auth/shared/login-aside.hbs',
  '/src/modules/auth/login/login-form.hbs',
  '/src/modules/auth/register/register-step1.hbs',
  '/src/modules/auth/register/register-step2.hbs',
  '/src/modules/auth/register/register-step3.hbs',
  '/src/modules/auth/password_reset/reset_password-step1.hbs',
  '/src/modules/auth/password_reset/reset_password-step2.hbs',
  '/src/modules/home/hero-search.hbs',
  '/src/modules/home/home-events-section.hbs',
  '/src/modules/home/home-mood-section.hbs',
  '/src/modules/profile/profile-aside.hbs',
  '/src/modules/profile/profile-form.hbs',
  '/src/modules/profile/profile-overview.hbs',
  '/src/modules/support/support-message-form.hbs',
  '/src/modules/support/support-messages.hbs',
  '/src/modules/support/support-status-badge.hbs',
  '/src/modules/support/support-ticket-form.hbs',
  '/src/modules/support/support-ticket-list.hbs',
  '/src/modules/profile/profile-overview.hbs',
  '/src/app/app-error.hbs',
  '/src/pages/event/event.hbs',
  '/src/pages/event-list/event-list.hbs',
  '/src/pages/home/home.hbs',
  '/src/pages/login/login.hbs',
  '/src/pages/not-found/not-found.hbs',
  '/src/pages/password_reset/password_reset.hbs',
  '/src/pages/profile/profile.hbs',
  '/src/pages/profile-settings/profile-settings.hbs',
  '/src/pages/register/register.hbs',
  '/src/pages/support-statistics/support-statistics.hbs',
  '/src/pages/support-widget/support-widget.hbs',
];

export const APP_SHELL_URLS = [
  '/',
  '/index.html',
  '/offline.html',
  '/runtime-config.js',
  '/manifest.webmanifest',
  '/public/static/favicons/apple-touch-icon.png',
  '/public/static/favicons/favicon-32x32.png',
  '/public/static/favicons/favicon-16x16.png',
  '/public/static/favicons/android-chrome-192x192.png',
  '/public/static/favicons/android-chrome-512x512.png',
  ...TEMPLATE_URLS,
];
